name: Code Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  npm:
    name: Npm Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v3
      - name: Setup Github Actions for Node.js
        uses: actions/setup-node@v3
      - name: npm clean-install --workspaces --include-workspace-root
        uses: thnetii/gh-actions/src/gh-actions-npm@main
        with:
          arguments: |
            clean-install
            --workspaces
            --include-workspace-root

  tsc:
    name: TypeScript type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v3
      - name: Setup Github Actions for Node.js
        uses: actions/setup-node@v3
      - run: npm clean-install --workspaces --include-workspace-root
      - name: tsc --noEmit -p ./jsconfig.json
        uses: thnetii/gh-actions/src/gh-actions-tsc@main
        with:
          arguments: |
            --noEmit
            -p
            ./jsconfig.json

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v3
      - name: Setup Github Actions for Node.js
        uses: actions/setup-node@v3
      - run: npm clean-install --workspaces --include-workspace-root
      - name: npm install --no-save @thnetii/eslint-formatter-gh-actions
        run: npm install --no-save https://gitpkg.now.sh/thnetii/gh-actions/src/eslint-formatter-gh-actions?main
      - name: eslint .
        run: npm exec -- eslint -f @thnetii/eslint-formatter-gh-actions .
