name: Code Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  npm:
    name: Npm Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v3
      - name: Setup Github Actions for Node.js
        uses: actions/setup-node@v3
      - name: npm clean-install --workspaces --include-workspace-root
        uses: thnetii/.github/actions/gh-actions-npm@main
        with:
          arguments: |
            clean-install
            --workspaces
            --include-workspace-root

  tsc:
    name: TypeScript type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v3
      - name: Setup Github Actions for Node.js
        uses: actions/setup-node@v3
      - run: npm clean-install --workspaces --include-workspace-root
      - name: tsc --noEmit -p ./jsconfig.json
        uses: thnetii/.github/actions/gh-actions-tsc@main
        with:
          arguments: |
            --noEmit
            -p
            ./jsconfig.json

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v3
      - name: Setup Github Actions for Node.js
        uses: actions/setup-node@v3
      - run: npm clean-install --workspaces --include-workspace-root
      - name: eslint .
        uses: thnetii/.github/actions/gh-actions-eslint@eslint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v3
      - name: Setup Github Actions for Node.js
        uses: actions/setup-node@v3
      - run: npm clean-install --workspaces --include-workspace-root
      - name: prettier --check .
        uses: thnetii/.github/actions/gh-actions-prettier@main
